server:
  port: 9004
eureka:
  instance:
    preferIpAddress: true
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://eureka-service.default.svc.cluster.local/eureka/
  healthcheck:
    enabled: true

spring:
  application:
    name: gateway

