eureka:
  instance:
    preferIpAddress: true
    hostname: produit-service
  client:
    serviceUrl:
      defaultZone: http://eureka-service.default.svc.cluster.local/eureka/
  healthcheck:
    enabled: true